name: Li Dong's Website
markdown: redcarpet
pygments: true
navigation:
 - title: Home
   url: index.html
 - title: Research
   url: research.html
 - title: Publication
   url: publication.html
 - title: Plan
   url: plan.html